services:
    core.animals_color_dispenser.animal_color_dispenser:
        class: CoreBundle\AnimalsColorDispenser\AnimalColorDispenser
        tags:
            - { name: twig.extension }
#    core.example:
#        class: CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
