<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BirdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BirdRepository extends EntityRepository
{
}
